# -*- coding: utf-8 -*-
"""CSES_Intro_IncreasingArray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

n = int(input())
numList = list(map(int, input().split()))
moves = 0
i = 0

while i < len(numList) - 1:
    if numList[i] > numList[i+1]:
        moves += (numList[i] - numList[i+1])
        numList[i+1] += (numList[i] - numList[i+1])
    i += 1

print(moves)