# -*- coding: utf-8 -*-
"""CSES_Intro_NumberSpiral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

t = int(input())
for _ in range(t):
    y, x = map(int, input().split())
    m = max(y, x)
    if m % 2 == 0:
        x, y = y, x   # mirror the even case onto the odd case's shape
    if x == m:
        ans = m*m - (y - 1)
    else:
        ans = (m - 1)**2 + x
    print(ans)