# -*- coding: utf-8 -*-
"""CSES_Intro_BitStrings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

n = int(input())
result = 2**n
m = 10**9 + 7

print(result%m)