# -*- coding: utf-8 -*-
"""CSES_Intro_MissingNum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

from collections import Counter

n = int(input())
nums = list(map(int, input().split()))
numSet = Counter(nums)

result = 0
for i in range(1, n + 1):
    if numSet[i] == 0:
        result = i
        break

print(result)