# -*- coding: utf-8 -*-
"""CSES_Intro_DnaSeq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

dna = str(input())
n = len(dna)
maxLen = 1
dnaLen = 1
i = 0
while i <=n and i+1<n:
  if dna[i] == dna[i+1]:
    dnaLen+=1
  else:
    dnaLen = 1
  i+=1
  maxLen = max(maxLen,dnaLen)

print(maxLen)