# -*- coding: utf-8 -*-
"""CSES_Intro_TrailingZeros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

n = int(input())
count = 0
power = 5
while power <= n:
    count += n // power
    power *= 5
print(count)