# -*- coding: utf-8 -*-
"""CSES_Intro_weird num.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixFORyjrZNtCrp5N74xVfxpMKQNjeSR
"""

num = int(input())
values = []

while True:
    values.append(str(num))
    if num == 1:
        break
    elif num % 2 == 0:
        num = num // 2
    else:
        num = (3 * num) + 1

result = " ".join(values)
print(result)